# Form implementation generated from reading ui file 'e:\Trading\python\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.CEWidget = QtWidgets.QWidget(self.widget)
        self.CEWidget.setGeometry(QtCore.QRect(0, 0, 313, 261))
        self.CEWidget.setStyleSheet("border: 1px solid red;")
        self.CEWidget.setObjectName("CEWidget")
        self.PWidget = QtWidgets.QWidget(self.widget)
        self.PWidget.setGeometry(QtCore.QRect(314, 0, 313, 261))
        self.PWidget.setStyleSheet("border: 1px solid red;")
        self.PWidget.setObjectName("PWidget")
        self.PEWidget = QtWidgets.QWidget(self.widget)
        self.PEWidget.setGeometry(QtCore.QRect(628, 0, 313, 261))
        self.PEWidget.setStyleSheet("border: 1px solid red;")
        self.PEWidget.setObjectName("PEWidget")
        self.verticalLayout_4.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
