# Form implementation generated from reading ui file 'e:\Trading\python\ui\Row.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Row(object):
    def setupUi(self, Row):
        Row.setObjectName("Row")
        Row.resize(319, 104)
        Row.setMaximumSize(QtCore.QSize(16777215, 104))
        Row.setStyleSheet("QWidget{\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    border: 1px solid grey;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    height: 100%;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Row)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(2, -1, 2, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lCallOIChange = QtWidgets.QLabel(Row)
        self.lCallOIChange.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lCallOIChange.setObjectName("lCallOIChange")
        self.horizontalLayout.addWidget(self.lCallOIChange)
        self.pbCall = QtWidgets.QPushButton(Row)
        self.pbCall.setObjectName("pbCall")
        self.horizontalLayout.addWidget(self.pbCall)
        self.lStrikePrice = QtWidgets.QLabel(Row)
        self.lStrikePrice.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lStrikePrice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lStrikePrice.setObjectName("lStrikePrice")
        self.horizontalLayout.addWidget(self.lStrikePrice)
        self.pbPut = QtWidgets.QPushButton(Row)
        self.pbPut.setStyleSheet("height: 100%")
        self.pbPut.setObjectName("pbPut")
        self.horizontalLayout.addWidget(self.pbPut)
        self.lPutOIChange = QtWidgets.QLabel(Row)
        self.lPutOIChange.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lPutOIChange.setObjectName("lPutOIChange")
        self.horizontalLayout.addWidget(self.lPutOIChange)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Row)
        QtCore.QMetaObject.connectSlotsByName(Row)

    def retranslateUi(self, Row):
        _translate = QtCore.QCoreApplication.translate
        Row.setWindowTitle(_translate("Row", "Form"))
        self.lCallOIChange.setText(_translate("Row", "NA"))
        self.pbCall.setText(_translate("Row", "LTP"))
        self.lStrikePrice.setText(_translate("Row", "Strike Price"))
        self.pbPut.setText(_translate("Row", "LTP"))
        self.lPutOIChange.setText(_translate("Row", "NA"))
